/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Memory
         * @description Save a session summary. Returns 422 if it contains a private key.
         */
        post: operations["save_memory_v1_memories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{topic_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Memory
         * @description Append to a topic, or replace it.
         *
         *     Appending is the default because Graphiti reconciles contradictions itself:
         *     the older fact is marked superseded rather than lost, which keeps the history
         *     of a decision readable.
         */
        patch: operations["update_memory_v1_memories__topic_key__patch"];
        trace?: never;
    };
    "/v1/memories/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Memories */
        get: operations["search_memories_v1_memories_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memory Context */
        get: operations["memory_context_v1_memories_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{episode_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Memory
         * @description Delete a memory. A uuid outside the caller's org is simply not found.
         */
        delete: operations["delete_memory_v1_memories__episode_uuid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_v1_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness for both stores. Unauthenticated on purpose — it reveals nothing.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ContextResponse */
        ContextResponse: {
            /** Project Key */
            project_key: string;
            /** Episodes */
            episodes: components["schemas"]["EpisodeOut"][];
        };
        /** DeleteResponse */
        DeleteResponse: {
            /** Episode Uuid */
            episode_uuid: string;
            /** Deleted */
            deleted: boolean;
        };
        /** EpisodeOut */
        EpisodeOut: {
            /** Uuid */
            uuid: string;
            /** Name */
            name: string;
            /** Content */
            content: string;
            /** Created At */
            created_at?: string | null;
            /** Author */
            author?: string | null;
            /**
             * Scope
             * @default private
             */
            scope: string;
        };
        /** FactOut */
        FactOut: {
            /** Name */
            name: string;
            /** Fact */
            fact: string;
            /** Created At */
            created_at?: string | null;
            /**
             * Superseded
             * @default false
             */
            superseded: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Postgres */
            postgres: boolean;
            /** Neo4J */
            neo4j: boolean;
            /** Extractor */
            extractor: string;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Id */
            id: string;
            /** Project Key */
            project_key: string;
            /** Display Name */
            display_name?: string | null;
            /**
             * Memory Count
             * @default 0
             */
            memory_count: number;
        };
        /** ProjectsResponse */
        ProjectsResponse: {
            /** Projects */
            projects: components["schemas"]["ProjectOut"][];
        };
        /** SaveMemoryRequest */
        SaveMemoryRequest: {
            /**
             * Project Key
             * @description Normalised git remote, e.g. github.com/acme/payments
             */
            project_key: string;
            /**
             * Summary
             * @description Markdown body written by the agent
             */
            summary: string;
            /**
             * Topic Key
             * @description Stable key for cross-session linking
             * @default
             */
            topic_key: string;
            /**
             * Tool
             * @description Which agent produced this
             * @default claude-code
             */
            tool: string;
        };
        /** SaveMemoryResponse */
        SaveMemoryResponse: {
            /** Id */
            id: string;
            /** Episode Uuid */
            episode_uuid: string;
            /** Name */
            name: string;
            /** Project Key */
            project_key: string;
            /** Author */
            author: string;
            /** Entity Count */
            entity_count: number;
            /** Relationship Count */
            relationship_count: number;
            /**
             * Scrubbed
             * @description What was redacted, empty if nothing
             * @default
             */
            scrubbed: string;
            /**
             * Degraded
             * @description Set when extraction failed and only the episode was stored
             */
            degraded?: string | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Project Key */
            project_key: string;
            /** Results */
            results: components["schemas"]["FactOut"][];
        };
        /** UpdateMemoryRequest */
        UpdateMemoryRequest: {
            /** Project Key */
            project_key: string;
            /** Update Summary */
            update_summary: string;
            /**
             * Replace
             * @description Delete prior episodes for this topic first
             * @default false
             */
            replace: boolean;
            /**
             * Tool
             * @default claude-code
             */
            tool: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    save_memory_v1_memories_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveMemoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveMemoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_memory_v1_memories__topic_key__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                topic_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveMemoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_memories_v1_memories_search_get: {
        parameters: {
            query: {
                project_key: string;
                q: string;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_context_v1_memories_context_get: {
        parameters: {
            query: {
                project_key: string;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_memory_v1_memories__episode_uuid__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                episode_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_v1_projects_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
