/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bootstrap State
         * @description Unauthenticated on purpose: the sign-in page needs to know whether to
         *     offer 'create your organisation' or 'sign in'.
         */
        get: operations["bootstrap_state_auth_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Only while the server is empty. The first person owns the organisation.
         */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign In */
        post: operations["sign_in_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign Out */
        post: operations["sign_out_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whoami */
        get: operations["whoami_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Set or change your own password. A user who has none yet (created by
         *     `drymem-admin` before identity existed) may set one without a current.
         */
        post: operations["change_password_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pending Invites */
        get: operations["pending_invites_auth_invites_get"];
        put?: never;
        /** Invite */
        post: operations["invite_auth_invites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/invites/{invite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Invite */
        delete: operations["revoke_invite_auth_invites__invite_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/invites/{token}/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Invite Public
         * @description What the invite page shows before the person has an account.
         */
        get: operations["invite_public_auth_invites__token__public_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept */
        post: operations["accept_auth_invites__token__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Sessions */
        get: operations["my_sessions_auth_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke My Session */
        delete: operations["revoke_my_session_auth_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Tokens */
        get: operations["my_tokens_auth_tokens_get"];
        put?: never;
        /**
         * New Token
         * @description For CI and other machines. Shown once; `drymem login` is the human path.
         */
        post: operations["new_token_auth_tokens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/tokens/{token_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Token */
        delete: operations["revoke_token_auth_tokens__token_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Device Start
         * @description Step one of `drymem login`. Unauthenticated: the CLI has nothing yet.
         */
        post: operations["device_start_auth_device_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/device/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Device Approve
         * @description Step two, in the browser, signed in.
         */
        post: operations["device_approve_auth_device_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/device/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Device Poll
         * @description Step three: the CLI collects its token. Handed over exactly once.
         */
        post: operations["device_poll_auth_device_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Memory
         * @description Save a session summary. Returns 422 if it contains a private key.
         */
        post: operations["save_memory_v1_memories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{topic_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Memory
         * @description Append to a topic, or replace it.
         *
         *     Appending is the default because Graphiti reconciles contradictions itself:
         *     the older fact is marked superseded rather than lost, which keeps the history
         *     of a decision readable.
         */
        patch: operations["update_memory_v1_memories__topic_key__patch"];
        trace?: never;
    };
    "/v1/memories/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Memories */
        get: operations["search_memories_v1_memories_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memory Context */
        get: operations["memory_context_v1_memories_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Topics
         * @description Every topic key already stored. Used by `drymem import` to stay idempotent.
         */
        get: operations["list_topics_v1_memories_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{episode_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Memory
         * @description Delete a memory. A uuid outside the caller's org is simply not found.
         */
        delete: operations["delete_memory_v1_memories__episode_uuid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{episode_uuid}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rate Memory
         * @description Record whether a retrieved memory was useful.
         *
         *     This is the pilot's precision metric: PLAN.md's 90% bar is measured from
         *     these rows, so the query that surfaced the memory is stored alongside the
         *     thumb — a rating with no query cannot be learned from.
         */
        post: operations["rate_memory_v1_memories__episode_uuid__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{episode_uuid}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Promote Memory
         * @description Share a memory with the project's members.
         *
         *     Only your own memory, and only into a project you belong to. Promoting an
         *     already-promoted memory succeeds without duplicating it, so a retry is safe.
         */
        post: operations["promote_memory_v1_memories__episode_uuid__promote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_key}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_v1_projects__project_key__members_get"];
        put?: never;
        /**
         * Add Member
         * @description Add someone to a project. They see its team memories, never its private ones.
         */
        post: operations["add_member_v1_projects__project_key__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover Skills
         * @description Subjects the team's memories keep returning to.
         *
         *     Which of them lack a skill is decided by the client, which is the only side
         *     that knows what is installed on this machine.
         */
        get: operations["discover_skills_v1_skills_discover_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills/distill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Distill Skill
         * @description Draft a SKILL.md from the memories about a subject.
         *
         *     The result is a draft for a person to review, never something installed
         *     automatically: a skill changes how every agent on the team behaves.
         */
        post: operations["distill_skill_v1_skills_distill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_v1_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Memory Schema
         * @description What a well-written memory looks like.
         *
         *     Served rather than duplicated in each client: the UI, the CLI and any future
         *     editor plugin all need the same list, and three hand-copied lists drift.
         */
        get: operations["memory_schema_v1_memories_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description The sittings this project's memories came out of.
         */
        get: operations["list_sessions_v1_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Everyone in this org, with counts only — never anyone's memories.
         */
        get: operations["list_users_v1_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Skills
         * @description Skills this project has published.
         */
        get: operations["list_skills_v1_skills_get"];
        put?: never;
        /**
         * Publish Skill
         * @description Publish a reviewed draft to the project. Publishing twice replaces it.
         */
        post: operations["publish_skill_v1_skills_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Skill */
        delete: operations["delete_skill_v1_skills__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami
         * @description Who this token belongs to. The UI needs it to say 'you' anywhere.
         */
        get: operations["whoami_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename Me
         * @description Set your display name. An empty name falls back to your email.
         */
        patch: operations["rename_me_v1_me_patch"];
        trace?: never;
    };
    "/v1/projects/{project_key}/members/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Member
         * @description Take someone off a project. Their own memories stay theirs and stay private.
         */
        delete: operations["remove_member_v1_projects__project_key__members__email__delete"];
        options?: never;
        head?: never;
        /** Set Member Role */
        patch: operations["set_member_role_v1_projects__project_key__members__email__patch"];
        trace?: never;
    };
    "/v1/projects/{project_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename Project
         * @description Give a project a readable name.
         *
         *     Declared *after* the member routes on purpose: `project_key` is a `:path`
         *     converter, so registered first it would greedily match
         *     `/v1/projects/<key>/members/<email>` as a project named
         *     "<key>/members/<email>". The key itself never changes — it is the normalised
         *     git remote, and changing it would split the team's memory in two.
         */
        patch: operations["rename_project_v1_projects__project_key__patch"];
        trace?: never;
    };
    "/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Project Overview
         * @description Everything the dashboard opens with, in one round trip.
         */
        get: operations["project_overview_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness for both stores. Unauthenticated on purpose — it reveals nothing.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptRequest */
        AcceptRequest: {
            /** Password */
            password: string;
            /**
             * Name
             * @default
             */
            name: string;
        };
        /** BootstrapOut */
        BootstrapOut: {
            /** Needs Setup */
            needs_setup: boolean;
            /** Org Name */
            org_name?: string | null;
            /**
             * Smtp Enabled
             * @default false
             */
            smtp_enabled: boolean;
        };
        /** ClusterOut */
        ClusterOut: {
            /** Topic */
            topic: string;
            /** Memory Count */
            memory_count: number;
            /**
             * Facts
             * @default []
             */
            facts: string[];
        };
        /** ContextResponse */
        ContextResponse: {
            /** Project Key */
            project_key: string;
            /** Episodes */
            episodes: components["schemas"]["EpisodeOut"][];
        };
        /** DeleteResponse */
        DeleteResponse: {
            /** Episode Uuid */
            episode_uuid: string;
            /** Deleted */
            deleted: boolean;
        };
        /** DeviceApprove */
        DeviceApprove: {
            /** User Code */
            user_code: string;
        };
        /** DevicePoll */
        DevicePoll: {
            /** Device Code */
            device_code: string;
        };
        /** DevicePollOut */
        DevicePollOut: {
            /** Status */
            status: string;
            /** Token */
            token?: string | null;
        };
        /** DeviceStart */
        DeviceStart: {
            /**
             * Label
             * @default
             */
            label: string;
        };
        /** DeviceStartOut */
        DeviceStartOut: {
            /** Device Code */
            device_code: string;
            /** User Code */
            user_code: string;
            /** Verification Url */
            verification_url: string;
            /**
             * Expires In
             * @default 900
             */
            expires_in: number;
            /**
             * Interval
             * @default 3
             */
            interval: number;
        };
        /** DiscoverResponse */
        DiscoverResponse: {
            /** Project Key */
            project_key: string;
            /** Clusters */
            clusters: components["schemas"]["ClusterOut"][];
        };
        /** DistillRequest */
        DistillRequest: {
            /** Project Key */
            project_key: string;
            /** Topic */
            topic: string;
        };
        /** DistillResponse */
        DistillResponse: {
            /** Topic */
            topic: string;
            /** Name */
            name: string;
            /** Content */
            content: string;
            /** Model */
            model: string;
            /** Memory Count */
            memory_count: number;
        };
        /** EpisodeOut */
        EpisodeOut: {
            /** Uuid */
            uuid: string;
            /** Name */
            name: string;
            /** Content */
            content: string;
            /** Created At */
            created_at?: string | null;
            /** Author */
            author?: string | null;
            /**
             * Scope
             * @default private
             */
            scope: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Type
             * @default note
             */
            type: string;
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Topic Key
             * @default
             */
            topic_key: string;
            /** Promoted At */
            promoted_at?: string | null;
            /**
             * Rating
             * @description +1, -1, or null when unrated
             */
            rating?: number | null;
        };
        /** FactOut */
        FactOut: {
            /** Name */
            name: string;
            /** Fact */
            fact: string;
            /** Created At */
            created_at?: string | null;
            /**
             * Superseded
             * @default false
             */
            superseded: boolean;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Rating
             * @description +1 or -1
             */
            rating: number;
            /**
             * Query
             * @description The search that surfaced this memory. A rating without it says 'this memory is bad'; with it, 'this memory is a bad answer to X'.
             * @default
             */
            query: string;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Episode Uuid */
            episode_uuid: string;
            /** Rating */
            rating: number;
            /** Query */
            query: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Postgres */
            postgres: boolean;
            /** Neo4J */
            neo4j: boolean;
            /** Extractor */
            extractor: string;
        };
        /** InviteOut */
        InviteOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Project Key */
            project_key?: string | null;
            /** Invited By */
            invited_by?: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Invite Url */
            invite_url?: string | null;
        };
        /** InvitePublicOut */
        InvitePublicOut: {
            /** Email */
            email: string;
            /** Org Name */
            org_name: string;
            /** Project Key */
            project_key?: string | null;
            /** Invited By */
            invited_by?: string | null;
        };
        /** InviteRequest */
        InviteRequest: {
            /** Email */
            email: string;
            /**
             * Role
             * @description member or admin
             * @default member
             */
            role: string;
            /**
             * Project Key
             * @description Also add them to this project
             */
            project_key?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MeOut */
        MeOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
            /** Org Id */
            org_id: string;
            /** Created At */
            created_at?: string | null;
        };
        /** MemberOut */
        MemberOut: {
            /** User Id */
            user_id: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
        };
        /** MemberRequest */
        MemberRequest: {
            /**
             * Email
             * @description An existing user in this org
             */
            email: string;
        };
        /** MemberRoleRequest */
        MemberRoleRequest: {
            /**
             * Role
             * @description member or admin
             */
            role: string;
        };
        /** MembersResponse */
        MembersResponse: {
            /** Project Key */
            project_key: string;
            /** Members */
            members: components["schemas"]["MemberOut"][];
        };
        /**
         * MemorySchemaResponse
         * @description The shape a well-written memory has. Served so clients need no copy of it.
         */
        MemorySchemaResponse: {
            /** Types */
            types: components["schemas"]["MemoryTypeOut"][];
            /** Sections */
            sections: string[];
            /** Template */
            template: string;
        };
        /** MemoryTypeOut */
        MemoryTypeOut: {
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /** OverviewResponse */
        OverviewResponse: {
            /** Project Key */
            project_key: string;
            /**
             * Memories
             * @default 0
             */
            memories: number;
            /**
             * Shared
             * @default 0
             */
            shared: number;
            /**
             * Sessions
             * @default 0
             */
            sessions: number;
            /**
             * Members
             * @default 0
             */
            members: number;
            /**
             * Skills
             * @default 0
             */
            skills: number;
            /**
             * Positive
             * @default 0
             */
            positive: number;
            /**
             * Negative
             * @default 0
             */
            negative: number;
            /**
             * By Type
             * @default {}
             */
            by_type: {
                [key: string]: number;
            };
        };
        /** PasswordRequest */
        PasswordRequest: {
            /**
             * Current
             * @default
             */
            current: string;
            /** New */
            new: string;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Id */
            id: string;
            /** Project Key */
            project_key: string;
            /** Display Name */
            display_name?: string | null;
            /**
             * Memory Count
             * @default 0
             */
            memory_count: number;
            /**
             * Positive
             * @default 0
             */
            positive: number;
            /**
             * Negative
             * @default 0
             */
            negative: number;
        };
        /** ProjectsResponse */
        ProjectsResponse: {
            /** Projects */
            projects: components["schemas"]["ProjectOut"][];
        };
        /** PromoteResponse */
        PromoteResponse: {
            /** Episode Uuid */
            episode_uuid: string;
            /** Scope */
            scope: string;
            /** Promoted At */
            promoted_at?: string | null;
        };
        /** PublishSkillRequest */
        PublishSkillRequest: {
            /** Project Key */
            project_key: string;
            /** Name */
            name: string;
            /**
             * Topic
             * @default
             */
            topic: string;
            /** Content */
            content: string;
            /** Model */
            model?: string | null;
            /**
             * Memory Count
             * @default 0
             */
            memory_count: number;
        };
        /** RenameMeRequest */
        RenameMeRequest: {
            /**
             * Name
             * @default
             */
            name: string;
        };
        /** RenameProjectRequest */
        RenameProjectRequest: {
            /**
             * Display Name
             * @default
             */
            display_name: string;
        };
        /** SaveMemoryRequest */
        SaveMemoryRequest: {
            /**
             * Project Key
             * @description Normalised git remote, e.g. github.com/acme/payments
             */
            project_key: string;
            /**
             * Summary
             * @description Markdown body written by the agent
             */
            summary: string;
            /**
             * Topic Key
             * @description Stable key for cross-session linking
             * @default
             */
            topic_key: string;
            /**
             * Tool
             * @description Which agent produced this
             * @default claude-code
             */
            tool: string;
            /**
             * Type
             * @description decision · architecture · bugfix · discovery · convention · note. An unknown value becomes 'note' rather than failing the save.
             * @default note
             */
            type: string;
            /**
             * Session Id
             * @description The agent run this came out of
             * @default
             */
            session_id: string;
        };
        /** SaveMemoryResponse */
        SaveMemoryResponse: {
            /** Id */
            id: string;
            /** Episode Uuid */
            episode_uuid: string;
            /** Name */
            name: string;
            /** Project Key */
            project_key: string;
            /** Author */
            author: string;
            /** Entity Count */
            entity_count: number;
            /** Relationship Count */
            relationship_count: number;
            /**
             * Scrubbed
             * @description What was redacted, empty if nothing
             * @default
             */
            scrubbed: string;
            /**
             * Degraded
             * @description Set when extraction failed and only the episode was stored
             */
            degraded?: string | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Project Key */
            project_key: string;
            /** Results */
            results: components["schemas"]["FactOut"][];
        };
        /** SessionsResponse */
        SessionsResponse: {
            /** Project Key */
            project_key: string;
            /** Sessions */
            sessions: components["schemas"]["drymem_server__api__schemas__SessionOut"][];
        };
        /** SignupRequest */
        SignupRequest: {
            /** Org Name */
            org_name: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
            /**
             * Name
             * @default
             */
            name: string;
        };
        /** SkillOut */
        SkillOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Topic */
            topic: string;
            /** Content */
            content: string;
            /** Author */
            author: string;
            /** Model */
            model?: string | null;
            /**
             * Memory Count
             * @default 0
             */
            memory_count: number;
            /** Updated At */
            updated_at?: string | null;
        };
        /** SkillsResponse */
        SkillsResponse: {
            /** Project Key */
            project_key: string;
            /** Skills */
            skills: components["schemas"]["SkillOut"][];
        };
        /** TokenOut */
        TokenOut: {
            /** Id */
            id: string;
            /** Label */
            label: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Token */
            token?: string | null;
        };
        /** TokenRequest */
        TokenRequest: {
            /**
             * Label
             * @default
             */
            label: string;
        };
        /** TopicsResponse */
        TopicsResponse: {
            /** Project Key */
            project_key: string;
            /** Topic Keys */
            topic_keys: string[];
        };
        /** UpdateMemoryRequest */
        UpdateMemoryRequest: {
            /** Project Key */
            project_key: string;
            /** Update Summary */
            update_summary: string;
            /**
             * Replace
             * @description Delete prior episodes for this topic first
             * @default false
             */
            replace: boolean;
            /**
             * Tool
             * @default claude-code
             */
            tool: string;
            /**
             * Type
             * @default note
             */
            type: string;
            /**
             * Session Id
             * @default
             */
            session_id: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
            /**
             * Memory Count
             * @default 0
             */
            memory_count: number;
            /**
             * Project Count
             * @default 0
             */
            project_count: number;
            /** Created At */
            created_at?: string | null;
        };
        /** UsersResponse */
        UsersResponse: {
            /** Users */
            users: components["schemas"]["UserOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WebSessionOut */
        WebSessionOut: {
            /** Id */
            id: string;
            /** User Agent */
            user_agent: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Seen At */
            last_seen_at: string | null;
            /** Current */
            current: boolean;
        };
        /** SessionOut */
        drymem_server__api__auth_routes__SessionOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string | null;
            /** Role */
            role: string;
            /** Org Id */
            org_id: string;
            /** Org Name */
            org_name: string;
        };
        /** SessionOut */
        drymem_server__api__schemas__SessionOut: {
            /** Session Id */
            session_id: string;
            /** Author */
            author: string;
            /** Memory Count */
            memory_count: number;
            /**
             * Shared
             * @default 0
             */
            shared: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Ended At
             * Format: date-time
             */
            ended_at: string;
            /**
             * Titles
             * @default []
             */
            titles: string[];
            /**
             * Synthetic
             * @description Grouped by author and day because no session id was recorded
             * @default false
             */
            synthetic: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    bootstrap_state_auth_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapOut"];
                };
            };
        };
    };
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["drymem_server__api__auth_routes__SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_in_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["drymem_server__api__auth_routes__SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_out_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    whoami_auth_session_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["drymem_server__api__auth_routes__SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_auth_password_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pending_invites_auth_invites_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_auth_invites_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_invite_auth_invites__invite_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                invite_id: string;
            };
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_public_auth_invites__token__public_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitePublicOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_auth_invites__token__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["drymem_server__api__auth_routes__SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_sessions_auth_sessions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebSessionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_my_session_auth_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_tokens_auth_tokens_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    new_token_auth_tokens_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_token_auth_tokens__token_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                token_id: string;
            };
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    device_start_auth_device_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceStart"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceStartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    device_approve_auth_device_approve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceApprove"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    device_poll_auth_device_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevicePoll"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevicePollOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_memory_v1_memories_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveMemoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveMemoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_memory_v1_memories__topic_key__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                topic_key: string;
            };
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveMemoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_memories_v1_memories_search_get: {
        parameters: {
            query: {
                project_key: string;
                q: string;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_context_v1_memories_context_get: {
        parameters: {
            query: {
                project_key: string;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_topics_v1_memories_topics_get: {
        parameters: {
            query: {
                project_key: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_memory_v1_memories__episode_uuid__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                episode_uuid: string;
            };
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rate_memory_v1_memories__episode_uuid__feedback_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                episode_uuid: string;
            };
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_memory_v1_memories__episode_uuid__promote_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                episode_uuid: string;
            };
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_v1_projects__project_key__members_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_key: string;
            };
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_v1_projects__project_key__members_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_key: string;
            };
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_skills_v1_skills_discover_get: {
        parameters: {
            query: {
                project_key: string;
                min_memories?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    distill_skill_v1_skills_distill_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DistillRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistillResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_v1_projects_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_schema_v1_memories_schema_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemorySchemaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_v1_sessions_get: {
        parameters: {
            query: {
                project_key: string;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_v1_users_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_v1_skills_get: {
        parameters: {
            query: {
                project_key: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_skill_v1_skills_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishSkillRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_skill_v1_skills__name__delete: {
        parameters: {
            query: {
                project_key: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whoami_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_me_v1_me_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_v1_projects__project_key__members__email__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_key: string;
                email: string;
            };
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_member_role_v1_projects__project_key__members__email__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_key: string;
                email: string;
            };
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_project_v1_projects__project_key__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_key: string;
            };
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_overview_v1_overview_get: {
        parameters: {
            query: {
                project_key: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                drymem_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
