/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Memory
         * @description Save a session summary. Returns 422 if it contains a private key.
         */
        post: operations["save_memory_v1_memories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{topic_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Memory
         * @description Append to a topic, or replace it.
         *
         *     Appending is the default because Graphiti reconciles contradictions itself:
         *     the older fact is marked superseded rather than lost, which keeps the history
         *     of a decision readable.
         */
        patch: operations["update_memory_v1_memories__topic_key__patch"];
        trace?: never;
    };
    "/v1/memories/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Memories */
        get: operations["search_memories_v1_memories_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memory Context */
        get: operations["memory_context_v1_memories_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Topics
         * @description Every topic key already stored. Used by `drymem import` to stay idempotent.
         */
        get: operations["list_topics_v1_memories_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{episode_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Memory
         * @description Delete a memory. A uuid outside the caller's org is simply not found.
         */
        delete: operations["delete_memory_v1_memories__episode_uuid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{episode_uuid}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rate Memory
         * @description Record whether a retrieved memory was useful.
         *
         *     This is the pilot's precision metric: PLAN.md's 90% bar is measured from
         *     these rows, so the query that surfaced the memory is stored alongside the
         *     thumb — a rating with no query cannot be learned from.
         */
        post: operations["rate_memory_v1_memories__episode_uuid__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{episode_uuid}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Promote Memory
         * @description Share a memory with the project's members.
         *
         *     Only your own memory, and only into a project you belong to. Promoting an
         *     already-promoted memory succeeds without duplicating it, so a retry is safe.
         */
        post: operations["promote_memory_v1_memories__episode_uuid__promote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_key}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_v1_projects__project_key__members_get"];
        put?: never;
        /**
         * Add Member
         * @description Add someone to a project. They see its team memories, never its private ones.
         */
        post: operations["add_member_v1_projects__project_key__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover Skills
         * @description Subjects the team's memories keep returning to.
         *
         *     Which of them lack a skill is decided by the client, which is the only side
         *     that knows what is installed on this machine.
         */
        get: operations["discover_skills_v1_skills_discover_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills/distill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Distill Skill
         * @description Draft a SKILL.md from the memories about a subject.
         *
         *     The result is a draft for a person to review, never something installed
         *     automatically: a skill changes how every agent on the team behaves.
         */
        post: operations["distill_skill_v1_skills_distill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_v1_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness for both stores. Unauthenticated on purpose — it reveals nothing.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClusterOut */
        ClusterOut: {
            /** Topic */
            topic: string;
            /** Memory Count */
            memory_count: number;
            /**
             * Facts
             * @default []
             */
            facts: string[];
        };
        /** ContextResponse */
        ContextResponse: {
            /** Project Key */
            project_key: string;
            /** Episodes */
            episodes: components["schemas"]["EpisodeOut"][];
        };
        /** DeleteResponse */
        DeleteResponse: {
            /** Episode Uuid */
            episode_uuid: string;
            /** Deleted */
            deleted: boolean;
        };
        /** DiscoverResponse */
        DiscoverResponse: {
            /** Project Key */
            project_key: string;
            /** Clusters */
            clusters: components["schemas"]["ClusterOut"][];
        };
        /** DistillRequest */
        DistillRequest: {
            /** Project Key */
            project_key: string;
            /** Topic */
            topic: string;
        };
        /** DistillResponse */
        DistillResponse: {
            /** Topic */
            topic: string;
            /** Name */
            name: string;
            /** Content */
            content: string;
            /** Model */
            model: string;
            /** Memory Count */
            memory_count: number;
        };
        /** EpisodeOut */
        EpisodeOut: {
            /** Uuid */
            uuid: string;
            /** Name */
            name: string;
            /** Content */
            content: string;
            /** Created At */
            created_at?: string | null;
            /** Author */
            author?: string | null;
            /**
             * Scope
             * @default private
             */
            scope: string;
        };
        /** FactOut */
        FactOut: {
            /** Name */
            name: string;
            /** Fact */
            fact: string;
            /** Created At */
            created_at?: string | null;
            /**
             * Superseded
             * @default false
             */
            superseded: boolean;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Rating
             * @description +1 or -1
             */
            rating: number;
            /**
             * Query
             * @description The search that surfaced this memory. A rating without it says 'this memory is bad'; with it, 'this memory is a bad answer to X'.
             * @default
             */
            query: string;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Episode Uuid */
            episode_uuid: string;
            /** Rating */
            rating: number;
            /** Query */
            query: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Postgres */
            postgres: boolean;
            /** Neo4J */
            neo4j: boolean;
            /** Extractor */
            extractor: string;
        };
        /** MemberOut */
        MemberOut: {
            /** User Id */
            user_id: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
        };
        /** MemberRequest */
        MemberRequest: {
            /**
             * Email
             * @description An existing user in this org
             */
            email: string;
        };
        /** MembersResponse */
        MembersResponse: {
            /** Project Key */
            project_key: string;
            /** Members */
            members: components["schemas"]["MemberOut"][];
        };
        /** ProjectOut */
        ProjectOut: {
            /** Id */
            id: string;
            /** Project Key */
            project_key: string;
            /** Display Name */
            display_name?: string | null;
            /**
             * Memory Count
             * @default 0
             */
            memory_count: number;
            /**
             * Positive
             * @default 0
             */
            positive: number;
            /**
             * Negative
             * @default 0
             */
            negative: number;
        };
        /** ProjectsResponse */
        ProjectsResponse: {
            /** Projects */
            projects: components["schemas"]["ProjectOut"][];
        };
        /** PromoteResponse */
        PromoteResponse: {
            /** Episode Uuid */
            episode_uuid: string;
            /** Scope */
            scope: string;
            /** Promoted At */
            promoted_at?: string | null;
        };
        /** SaveMemoryRequest */
        SaveMemoryRequest: {
            /**
             * Project Key
             * @description Normalised git remote, e.g. github.com/acme/payments
             */
            project_key: string;
            /**
             * Summary
             * @description Markdown body written by the agent
             */
            summary: string;
            /**
             * Topic Key
             * @description Stable key for cross-session linking
             * @default
             */
            topic_key: string;
            /**
             * Tool
             * @description Which agent produced this
             * @default claude-code
             */
            tool: string;
        };
        /** SaveMemoryResponse */
        SaveMemoryResponse: {
            /** Id */
            id: string;
            /** Episode Uuid */
            episode_uuid: string;
            /** Name */
            name: string;
            /** Project Key */
            project_key: string;
            /** Author */
            author: string;
            /** Entity Count */
            entity_count: number;
            /** Relationship Count */
            relationship_count: number;
            /**
             * Scrubbed
             * @description What was redacted, empty if nothing
             * @default
             */
            scrubbed: string;
            /**
             * Degraded
             * @description Set when extraction failed and only the episode was stored
             */
            degraded?: string | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Project Key */
            project_key: string;
            /** Results */
            results: components["schemas"]["FactOut"][];
        };
        /** TopicsResponse */
        TopicsResponse: {
            /** Project Key */
            project_key: string;
            /** Topic Keys */
            topic_keys: string[];
        };
        /** UpdateMemoryRequest */
        UpdateMemoryRequest: {
            /** Project Key */
            project_key: string;
            /** Update Summary */
            update_summary: string;
            /**
             * Replace
             * @description Delete prior episodes for this topic first
             * @default false
             */
            replace: boolean;
            /**
             * Tool
             * @default claude-code
             */
            tool: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    save_memory_v1_memories_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveMemoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveMemoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_memory_v1_memories__topic_key__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                topic_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveMemoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_memories_v1_memories_search_get: {
        parameters: {
            query: {
                project_key: string;
                q: string;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_context_v1_memories_context_get: {
        parameters: {
            query: {
                project_key: string;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_topics_v1_memories_topics_get: {
        parameters: {
            query: {
                project_key: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_memory_v1_memories__episode_uuid__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                episode_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rate_memory_v1_memories__episode_uuid__feedback_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                episode_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_memory_v1_memories__episode_uuid__promote_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                episode_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_v1_projects__project_key__members_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_v1_projects__project_key__members_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_skills_v1_skills_discover_get: {
        parameters: {
            query: {
                project_key: string;
                min_memories?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    distill_skill_v1_skills_distill_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DistillRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistillResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_v1_projects_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
