import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { CallToolRequestSchema, ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import { fileURLToPath } from "url";
import { dirname } from "path";

import { SaveMemoryUseCase, SearchMemoriesUseCase, GetContextUseCase, DeleteMemoryUseCase } from "../../core/use-cases/memory-use-cases.js";
import { runMigrations } from "../../infrastructure/database/migrations.js";

console.log = console.error;
console.info = console.error;

runMigrations();

const server = new Server(
  { name: "drymem-agent", version: "1.0.0" },
  { capabilities: { tools: {} } }
);

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const currentProjectPath = process.cwd();

function detectProjectPath(args: any): string {
  if (args && args.project_path) {
    return args.project_path;
  }
  return currentProjectPath;
}

server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: "mem_search",
        description: "Searches the developer memory by keywords.",
        inputSchema: {
          type: "object",
          properties: {
            keyword: { type: "string" },
            project_path: { type: "string" }
          },
          required: ["keyword"]
        }
      },
      {
        name: "mem_context",
        description: "Returns the recent timeline of memories for this project.",
        inputSchema: {
          type: "object",
          properties: {
            project_path: { type: "string" }
          }
        }
      },
      {
        name: "mem_delete",
        description: "Applies a soft-delete to a specific memory.",
        inputSchema: {
          type: "object",
          properties: {
            topic_key: { type: "string" },
            project_path: { type: "string" }
          },
          required: ["topic_key"]
        }
      },
      {
        name: "mem_finalize_session",
        description: "Creates a high-quality technical summary of an entire session.",
        inputSchema: {
          type: "object",
          properties: {
            topic_key: { type: "string" },
            project_path: { type: "string" },
            problem_statement: { type: "string" },
            solution_summary: { type: "string" },
            affected_files: { type: "string" },
            key_learnings: { type: "string" }
          },
          required: ["topic_key", "problem_statement", "solution_summary", "affected_files", "key_learnings"]
        }
      }
    ]
  };
});

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;
  
  try {
    if (name === "mem_search") {
      const { keyword } = args as any;
      const project_path = detectProjectPath(args);
      const results = SearchMemoriesUseCase.execute(keyword, project_path);
      return { content: [{ type: "text", text: results.length ? JSON.stringify(results, null, 2) : "No memories found." }] };
    }

    if (name === "mem_context") {
      const project_path = detectProjectPath(args);
      const results = GetContextUseCase.execute(project_path);
      return { content: [{ type: "text", text: results.length ? JSON.stringify(results, null, 2) : "No recent context." }] };
    }

    if (name === "mem_delete") {
      const { topic_key } = args as any;
      const project_path = detectProjectPath(args);
      const success = DeleteMemoryUseCase.execute(topic_key, project_path);
      return { content: [{ type: "text", text: success ? `Memory '${topic_key}' deleted (soft-delete).` : "Memory not found." }] };
    }

    if (name === "mem_finalize_session") {
      const sessionArgs = args as {
        topic_key: string;
        project_path: string;
        problem_statement: string;
        solution_summary: string;
        affected_files: string;
        key_learnings: string;
        scope?: string;
      };
      
      const project_path = detectProjectPath(sessionArgs);
      const { topic_key, problem_statement, solution_summary, affected_files, key_learnings } = sessionArgs;
      
      // Build markdownSummary as a single clean string without leading/trailing whitespace
      const markdownSummary = `# Session Summary: ${topic_key}

## Problem Statement
${problem_statement}

## Solution Summary
${solution_summary}

## Affected Files
${affected_files}

## Key Learnings
${key_learnings}

---
*Generated by drymem MCP server*`;
      
      const result = SaveMemoryUseCase.execute({
        topic_key: topic_key,
        project_path: project_path,
        scope: sessionArgs.scope || "project",
        query_input: problem_statement,
        proposed_code: "",
        content: markdownSummary,
        status: "ACCEPTED"
      });
      
      if (result.success) {
        return { content: [{ type: "text", text: `Session finalized and saved successfully: ${topic_key}` }] };
      } else {
        return { content: [{ type: "text", text: `SQLite database error: ${result.error}` }] };
      }
    }

    throw new Error(`Tool not found: ${name}`);
  } catch (error: any) {
    console.error(`Fatal error in mem_finalize_session: ${error.message}`);
    console.error(error.stack);
    return { content: [{ type: "text", text: `Internal error: ${error.message}` }], isError: true };
  }
});

async function main() {

  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error(`Drymem MCP server running (project_path: ${currentProjectPath})`);
}

main().catch((error) => {
  console.error("Fatal error starting the server:", error);
  process.exit(1);
});
